import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ApiData from "../sevices/apiData";
import styles from "../styles/Home.module.scss";

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>This is something</p>
        <div className={styles.navLinks}>
          <Link href="/about">
            <a className={styles.link}>About</a>
          </Link>
          <Link href="/avatars">
            <a className={styles.link}>Avatars</a>
          </Link>
          <Link href="/characters">
            <a className={styles.link}>Characters</a>
          </Link>
        </div>
        <ul className={styles.grid}>
          {data.map((e: any) => {
            const { id, name } = e;
            const to = name.replaceAll(/ /g, "-");
            return (
              <Link href={`/details/${to.toLowerCase()}`} key={id}>
                <li className={styles.card}>{name}</li>
              </Link>
            );
          })}
        </ul>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const apiData = new ApiData();
  const results = await apiData.getData();

  return {
    props: {
      data: results,
    },
  };
}
